========
完善历史
========

`查看Go语言资料收集 <https://github.com/wonderfo/wonderfogo/wiki>`_	

说明
====

登记资料内容变化，以及重大格式调整历史

明细
====

* **2012-03-31**

	#. 完善： Go1正式发布，更新相关资料
	#. 新增： monnand 和 AllenDangm 的博客
        #. 完善： appspot.com 改成 appsp0t.com

* **2012-02-11**

	#. 新增： 最新weekly版2012-02-07
	#. 新增： 添加Go1最新资料

* **2012-02-05**

	#. 新增： 添加Go1最新消息
	#. 修正： 一些错误和重复文字

* **2012-01-30**

	#. 调整： 最新weekly版2012-01-27
	#. 修正： 根据 **monnand** 提醒，删除Andrew Gerrand 错误介绍，和 "使用GNU调试器调试Go代码"标题错误
	#. 修正： 修正上次发布调整时弄错的多个链接和文字

* **2012-01-21**

    #. 调整：最新weekly版2012-01-20
    #. 调整：社区项目迁移到参考手册
    #. 调整：邮件列表独立成组，并合入 golang-china
    #. 调整：修正几个错误连接
    #. 调整：在线代码测试整理，并合入 学习资料
    #. 调整：将版本安装独立处理
    #. 添加：Go1发版需解决问题
    #. 优化：部分文字

* **2012-01-17**

    #. 调整：最新windows的weekly版2012-01-15
    #. 调整：Gopher Times 网站大调整，因此相关链接取消了
    #. 调整：仪表盘的介绍有误，已修改。并将名称改为“社区项目”
    #. 添加：无心云博客
    #. 优化：文字调整

* **2011-12-31**

    #. 添加：王益、Crane博客
    #. 添加：王益《关于go语言》
    #. 优化：调整文字

* **2011-12-29**

    #. 添加：根据 **四月份平民** 建议，添加教程 《Go Book》
    #. 添加：柴树杉的项目 密码生成器 PwdGen 
    #. 添加：陈钢、lvyi博客
    #. 添加：韦光京《Go语言Web开发》 柴树杉《Go集成C和C++代码》
    #. 调整：调整一些错误或不完善链接 
    #. 优化：显示排版等

* **2011-12-26**

    #. 添加：Uniqush 项目
    #. 添加：Go版本发布的邮件列表
    #. 添加：Tim在go发布时的一篇评测文章
    #. 添加：G1反馈贴
    #. 优化：“产品实践”和“各方评价”合并为“实践与评价”
    #. 优化：格式、学习体会

* **2011-12-24**

    #. 添加：根据 **Yili Zhao** 建议，添加专题文章 《Experimenting with Cgo》
    #. 添加：根据 **四月份平民** 建议，添加教程 《GoLang Tutorials》
    #. 添加：GAE支持邮件列表
    #. 添加：《G1 计划》的链接
    #. 添加：《Go 1 预览》的译文链接
    #. 添加：windows版本信息
    #. 添加：添加另一版的《Go语言-互联网时代的C》 视频
    #. 优化：格式、说明，修正链接错误


* **2011-12-22**

    #. 修正：根据 **Howard Fan** 提出的有关 ken 的介绍错误进行修正
    #. 添加：更多内容
    #. 优化：对格式进行大调整，更简洁实用

* **2011-12-18**

    #. 创建：将资料整理了一下，并同步到 GitHub 和 新浪

